spring.application.name=prepjob
server.port=${PORT:8080}
jwt.secret = ${JWT_SECRET}
gemini.api.url=${GEMINI_URL}
gemini.api.key=${GEMINI_KEY}
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true